config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: redirect("/home")
  get "/home",  to: "home#index"

  resources :users, only: [] do
    post :follow, to: "followers#follow"
    delete :unfollow, to: "followers#unfollow"
    resources :posts, only: [ :index ]
  end

  resources :posts, except: [ :index ] do
    resources :comments, only: [ :create, :destroy ]
    post "like", to: "likes#create"
    delete "unlike", to: "likes#destroy"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :text, presence: true
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"

  validates :follower_id, uniqueness: { scope: :following_id, message: "Вы уже подписаны на этого пользователя" }

  validate :cannot_follow_self

  private

  def cannot_follow_self
    if follower_id == following_id
      errors.add(:base, "Нельзя подписаться на самого себя")
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :post
  
    validates :user_id, uniqueness: { scope: :post_id, message: "Вы уже поставили лайк этому посту" }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :images, presence: true, content_type: [ "image/png", "image/jpeg" ], size: { less_than: 5.megabytes }
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise   :database_authenticatable,
           :registerable,
           :validatable

  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 75 }
  validates :avatar, content_type: [ "image/png", "image/jpeg" ]

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar

  # получить список подписчиков
  has_many :follower_relationships, class_name: "Follower", foreign_key: "following_id"
  has_many :followers, through: :follower_relationships, source: :follower

  # получить список подписок
  has_many :following_relationships, class_name: "Follower", foreign_key: "follower_id"
  has_many :following, through: :following_relationships, source: :following

  def liked?(post)
    post.likes.where(user_id: self.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: { modern: true }
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username, :email, :bio,  :password, :password_confirmation ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :username, :avatar, :email, :bio, :password, :password_confirmation, :current_password ])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, :check_owner, only: [ :destroy ]

  def create
    @comment  = current_user.comments.new(comment_params)

    if @comment.save
      redirect_to post_path(id: comment_params[:post_id]), notice: "Комментарий успешно добавлен"
    else
      redirect_to post_path(id: comment_params[:post_id]), alert: "Произошла ошибка при добавлении комментария"
    end
  end

  def destroy
    if @comment.destroy
      redirect_to post_path(id: comment_params[:post_id]), notice: "Комментарий был удалён"
    else
      redirect_to post_path(id: comment_params[:post_id]), alert: "Произошла ошибка при удалении комментария"
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def check_owner
    if @comment.user_id != current_user.id
      flash[:error] = "У вас нет прав на удаление этого коментария"
      redirect_to @comment.post
    end
  end

  def comment_params
    params.permit(:text, :post_id)
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :no_self_follow, only: [ :follow ]

  def follow
    @follow = Follower.find_or_initialize_by(follower_id: current_user.id, following_id: params[:user_id])

    if @follow.new_record? && @follow.save
      redirect_to user_posts_path(user_id: params[:user_id]), notice: "Вы подписались на аккаунт"
    else
      redirect_to user_posts_path(user_id: params[:user_id]), alert: "Не удалось подписаться"
    end
  end

  def unfollow
    @follow = Follower.find_by(follower_id: current_user.id, following_id: params[:user_id])

    if @follow
      @follow.destroy
      redirect_to user_posts_path(user_id: params[:user_id]), notice: "Вы успешно отписались"
    else
      redirect_to user_posts_path(user_id: params[:user_id]), alert: "Что-то пошло не так при отписке"
    end
  end

  def no_self_follow
    if current_user.id.to_s == params[:user_id]
      redirect_to user_posts_path(user_id: params[:user_id]), alert: "Нельзя подписаться на самого себя"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, :set_like

  def create
    
    if @like
      render json: 
      { error: "You have already liked this post" }, status: :unprocessable_entity
    else
      @post.likes.create(user_id: current_user.id)
      respond_to do |format|
        format.json { render json: { liked: true, likes_count: @post.likes.count } }
      end
    end
  end

  def destroy
    if @like
      @like.destroy
      respond_to do |format|
        format.json { render json: { liked: false, likes_count: @post.likes.count } }
      end
    else
      render json: 
      { error: "Like does not exist" }, status: :not_found
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_like
    @like = @post.likes.find_by(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [ :edit, :update, :show, :destroy ]
  before_action :check_owner, only: [ :edit, :update, :destroy ]

  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(user_id: @user.id).order(created_at: :desc)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post, notice: "Пост был успешно создан!"
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
      if @post.update(post_params)
        redirect_to @post, notice: "Пост был успешно обновлён!"
      else
        render "edit", status: :unprocessable_entity
      end
  end

  def destroy
    if @post.destroy
      redirect_to root_path, notice: "Пост был успешно удалён!"
    else
      redirect_to root_path, alert: "Произошла ошибка при удалении"
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def check_owner
    if @post.user_id != current_user.id
      redirect_to @post, alert: "Вы не являетесь владельцем данного поста"
    end
  end

  def post_params
    params.require(:post).permit(:description, images: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% content_for :title, "Лента" %>

<% @posts.each do |post| %>
  <%= render(Posts::CardComponent.new(post)) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Final Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="preload" href="https://code.jquery.com/jquery-3.6.0.min.js" as="script">
    <link rel="preload" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js" as="script">
    <link rel="preload" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" as="script">
    
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# Лайки асинхронно %>
    <script defer>
      async function toggleLike(postId, isLiked){
        const url = isLiked ? `/posts/${postId}/unlike` : `/posts/${postId}/like`;
        const method = isLiked ? 'DELETE' : 'POST';

        console.log(url, method)

        try {
          const response = await fetch(url, {
            method: method,
            headers: {
              'Content-Type': 'application/json',
              'Accept': 'application/json',
              'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').content
            },
            credentials: 'same-origin'
          });

          const data = await response.json();

          // Обновляем счетчик лайков
          document.getElementById(`like-count-${postId}`).innerText = `${data.likes_count}`;

          const likeButton = document.getElementById(`like-button-${postId}`);
          const svg = document.getElementById(`svg-button-${postId}`);

          likeButton.setAttribute('onclick', `toggleLike(${postId}, ${data.liked})`);
          color = data.liked ? "#ff0000" : "#000"
          svg.setAttribute('fill', color);

        } catch (error) {
      }
      }
    </script>
  </head>

  <body class="bg-white max-w-lg mx-auto h-screen flex flex-col">
    <%= render(HeaderComponent.new) %>

    <%= render(MessageComponent.new(notice: notice, alert: alert)) %>

    <main class="flex-grow flex-col items-center justify-center">
      <%= yield %>
    </main>

    <%= render(FooterComponent.new) %>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js"></script>
    <script>
      $(document).ready(function(){
        $('.slider').imagesLoaded().always(function() {
          $('.slider').slick({
            dots: true,
            infinite: true,
            speed: 300,
            slidesToShow: 1,
            adaptiveHeight: true
          });
        });
      });
    </script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Final Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
 
  <body class="bg-stone-50 max-w-lg mx-auto h-screen">
    <%= render(MessageComponent.new(notice: notice, alert: alert)) %>

    <% if @user.errors.any? %>
      <%= render(MessageComponent.new(errors: @user.errors.messages))%>
    <% end %>

    <main class="flex flex-col items-center h-full justify-center"> 
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/edit.html.erb
<% content_for :title, "Редактирование поста" %>

<div class="h-full px-3 grid place-items-center">
  <%= form_with(model: @post, class: "space-y-4 w-full") do |f| %>
    <div class="flex flex-col">
      <%= f.label :description, class: "text-sm font-medium text-gray-700" %>
      <%= f.text_area :description, class: "mt-1 p-2 w-full border border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500" %>
    </div>

    <div class="flex flex-col">
      <%= f.label :images, "Фотографии", class: "text-sm font-medium text-gray-700" %>
  
      <!-- Отображение существующих изображений -->
      <% if @post.images.attached? %>
        <div class="grid grid-cols-3 gap-2 my-2">
          <% @post.images.each do |image| %>
            <div class="relative group">
              <%= image_tag image, class: "w-full h-24 object-cover rounded-md" %>
            </div>
          <% end %>
        </div>
      <% end %>

      <!-- Поле для загрузки новых изображений -->
      <%= f.file_field :images, 
                      multiple: true, 
                      accept: "image/jpeg, image/jpg, image/png", 
                      class: "mt-1 p-2 w-full border border-gray-300 rounded-md shadow-sm file:mr-4 file:py-2 file:px-4 file:border-0 file:text-sm file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100" %>
    </div>

    <div>
      <%= f.submit "Редактировать", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<% content_for :title, @user.username %>

<div class="flex items-start space-y-0 space-x-8 py-8 px-4">
    <!-- Avatar -->
    <div class="w-32 h-32 min-w-fit">
        <%= image_tag(@user.avatar.present? ? @user.avatar : 'default_avatar.png', class: "rounded-full border-4 border-white shadow-lg w-32 h-32") %>
    </div>

    <!-- Profile Info -->
    <div class="flex-1 space-y-4 w">
        <!-- Username and Action Button -->
        <div class="flex items-center space-x-4">
            <h1 class="text-2xl font-light">
                <%=@user.username%>
            </h1>
            
        </div>

        <!-- Stats -->
        <div class="flex space-x-8">
            <div class="text-center">
                <span class="font-semibold">
                    <%=@posts.count%>
                </span>
                <span class="block text-gray-600 text-sm">Публикации</span>
            </div>
            <div class="text-center">
                <span class="font-semibold">
                    <%=@user.followers.count%>
                </span>
                <span class="block text-gray-600 text-sm">Подписчики</span>
            </div>
            <div class="text-center">
                <span class="font-semibold">
                    <%=@user.following.count%>
                </span>
                <span class="block text-gray-600 text-sm">Подписки</span>
            </div>
        </div>
        <div>
            <% if @user.id == current_user.id %>
                
                <%= button_to edit_user_registration_path, class: "bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors w-full cursor-pointer", method: :get do%>
                    Редактировать профиль
                <%end%>

            <%else%>

                <% if @user.followers.where(id: current_user.id).present? %>
                    <%= button_to user_unfollow_path(user_id: @user.id), class: "bg-slate-500 hover:bg-slate-600 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors w-full", method: :delete do%>
                        Отписаться
                    <%end%>
                <% else %>
                    <%= button_to user_follow_path(user_id: @user.id), class: "bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors w-full" do%>
                        Подписаться
                    <%end%>
                <% end %>
                 
            <% end %>
        </div>
        
    </div>  
   
</div>

<!-- Bio -->
 <div class="text-gray-800 w-1/2">
    <p class="break-words whitespace-normal overflow-hidden">
        <%=@user.bio%>
    </p>
</div>

<hr class="border-gray-200">

<div class="">
    <% @posts.each do |post| %>
        <%= render(Posts::CardComponent.new(post)) %>
    <% end %>
</div>  

app/views/posts/new.html.erb
<% content_for :title, "Создание поста" %>

<% if @post.errors.any? %>
  <%= render(MessageComponent.new(errors: @post.errors.messages))%>
<% end %>

<div class="h-full px-3 grid place-items-center">
  <%= form_with(model: @post, class: "space-y-6 w-full") do |f| %>
    <!-- Поле для описания -->
    <div class="flex flex-col">
      <%= f.label "Описание", class: "text-sm font-medium text-gray-700 mb-1" %>
      <%= f.text_area :description, class: "mt-1 p-3 w-full border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent placeholder-gray-400", placeholder: "Добавьте описание..." %>
    </div>

    <!-- Поле для загрузки изображений -->
    <div class="flex flex-col">
      <%= f.label :images, "Фотографии", class: "text-sm font-medium text-gray-700 mb-1" %>
      <%= f.file_field :images, multiple: true, accept: "image/jpeg, image/jpg, image/png", class: "mt-1 p-2 w-full border border-gray-300 rounded-lg shadow-sm file:mr-4 file:py-2 file:px-4 file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" %>
    </div>

    <!-- Кнопка отправки -->
    <div>
      <%= f.submit "Опубликовать", class: "w-full py-3 px-4 bg-blue-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<% content_for :title, "Просмотр поста" %>

<%= render(Posts::CardComponent.new(@post)) %>

<%= form_with url: post_comments_path(post_id: @post.id), class: "mb-4" do |f| %>
  <div class="flex items-center space-x-2">
    <%= f.text_field :text, autofocus: true, placeholder: "Оставьте комментарий...", class: "flex-1 p-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" %>
    <%= f.submit "Отправить", class: "px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2" %>
  </div>
<% end %>

<% unless @post.comments.empty? %>
  <div class="space-y-4">
    <% @post.comments.each do |comment| %>
      <div class="bg-white p-4 rounded-lg shadow-sm">
        <div class="flex items-center justify-between">
          <div class="flex items-center space-x-2">
            <%= image_tag(comment.user.avatar.present? ? comment.user.avatar : 'default_avatar.png', class: "w-10 h-10 rounded-full") %>
            <p class="font-semibold text-sm">
              <%= link_to user_posts_path(user_id: comment.user.id) do %>
                <%= comment.user.username %>
                <%end%>
            </p>
          </div>
          <% if current_user.id == comment.user_id %>
            <%= button_to "Удалить", post_comment_path(post_id: @post.id, id: comment.id), method: :delete, class: "text-red-500 text-sm hover:text-red-700" %>
          <% end %>
        </div>
        <p class="mt-2 text-sm text-gray-700 break-words whitespace-normal"><%= comment.text %></p>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="text-gray-500 text-center py-4">Список комментариев пуст</p>
<% end %>

<script>
    popupMenu = document.getElementById('popup-menu');

    document.getElementById('more-options').addEventListener('click', function() {
        popupMenu.classList.toggle('hidden');
    });
</script>